

export const listIcon = [
    'AndroidOutlined',
    'AppleOutlined',
    'WindowsOutlined',
    'IeOutlined',
    'ChromeOutlined',
    'GithubOutlined',
    // 'AliwangwangOutlined',
    'DingdingOutlined',
    'WeiboOutlined',
    'SkypeOutlined',
    'GooglePlusOutlined',
    'GoogleOutlined',
    // 'ZhihuOutlined',
    // 'DribbbleSquareOutlined',
    // 'SketchOutlined',
    'TwitterOutlined',
    'QqOutlined',
    'DropboxOutlined',
    'CodepenCircleOutlined',
    'SlackOutlined',
    'InstagramOutlined',
    // 'YuqueOutlined',
    'SlackSquareOutlined',
    'AlipayOutlined',
    'FacebookOutlined',
    'MediumWorkmarkOutlined',
    'WechatOutlined',
    'YoutubeOutlined',
    'GitlabOutlined',
    'CodepenOutlined',
    'AntDesignOutlined',
    // 'BehanceOutlined',
    'AlibabaOutlined',
    'YahooOutlined',
    // 'BehanceSquareOutlined',
    'AntCloudOutlined',
    'CodeSandboxOutlined',
    'MediumOutlined',
    'AlipayCircleOutlined',
    'Html5Outlined',
    'TaobaoOutlined',
    'LinkedinOutlined',
    'AmazonOutlined',
    'AliyunOutlined',
    'DribbbleOutlined',
    'RedditOutlined',
    // 'GlobalOutlined',
    'PhoneOutlined',
    'MailOutlined',
    'SendOutlined',
    'ShopOutlined',
    'SaveOutlined',
    'WhatsAppOutlined'
]